In [1]:
apple = '''
今天揭曉 美首位女總統？ 瘋狂素人總統？
川普反移民 想靠「隱性支持者翻盤」 希拉蕊 掃拉丁裔及婦女票
2016年11月09日      

．希拉蕊目前形勢樂觀，媒體預估能順利當選。法新社 
．川普以政治素人之姿，離經叛道的競選方式，也吸引大批支持者。美聯社
最後衝刺
【綜合報導】全球矚目的美國大選，昨天投票，究竟美國將出現首位女總統希拉蕊，或政治素人兼狂人川普將入主白宮，左右未來4年全球政經情勢，預計台灣時間今天中午揭曉。美國主流媒體預測希拉蕊能拿下過半數、逾270張選舉人票當選；破紀錄的拉丁裔和女性選民提前投票，也對她有利，但截至台灣時間昨深夜最早開出普選票的新罕布夏州3城鎮，川普暫居領先。

現年69歲的民主黨候選人希拉蕊（Hillary Clinton）、70歲的共和黨候選人川普（Donald Trump），前天把握最後時間催票。希拉蕊昨晨在紐約州住家附近小學投票站投下一票。現場約150多名支持者，高喊「女總統！」（Madam President）。她投票後微笑說：「我很高興，超級高興。看見這些朋友和鄰居，我好開心。」 


最後衝刺 
川普前天連跑5州造勢，包括選情緊繃的北卡羅萊納州。美聯社

希拉蕊選情樂觀，前晚在北卡羅萊納州的造勢活動延續到昨凌晨，氣氛熱烈。美聯社

川普3城鎮領先
新罕布夏州數城鎮昨率先在午夜後開放投票，是全美最早的地區之一。當地小鎮「迪克斯維爾山口」8個登記選民完成投票後即開票，希拉蕊以4比2領先，投給希拉蕊的旅社員工說：「她堅強、有經驗，會領導國家走上正確方向。」當地人杜爾森說：「國家必須向前，我不信川普能帶我們走向建設性道路。」不過該州3城鎮開票後，川普以32比25領先，但仍不足以看出該州4張選舉人票歸屬。 


4300萬人先投票
全美已有逾4300萬人完成提前投票，拉丁裔尤其踴躍，與反移民的川普相比，他們傾巢而出支持希拉蕊。佛羅里達大學提前投票專家史密斯說，到上周三為止：「超過42.9萬的拉丁裔完成提前投票，是4年前的158%。」他也觀察到比過去更多的女性參與提前投票：「她們支持民主黨，或非2大黨，這是所謂的『川普效應』，你若要說誰阻斷川普當選，那就是女性和少數族裔，尤其拉丁裔。」
形勢樂觀的希拉蕊，前晚在費城的晚會有4萬人參加，寫下她最多人參與造勢的紀錄，總統歐巴馬、「工人皇帝」布魯斯史普林斯汀為她站台；在北卡羅萊納州，則有「女神卡卡」（Lady Gaga）助威。希拉蕊說：「這次大選有很明確的選擇，要分裂還是團結、要堅強穩定的領導人，或是將一切置於險境的自走砲？」對於期待看到女性當選的人，她疾呼：「讓我們一起寫下歷史吧！」
川普雖看似處於劣勢，身旁也沒有明星助陣，但他自信擁有許多「隱性支持者」，能在最後翻轉選情。
川普前天勤跑5州造勢，大罵舞弊的制度、騙人的媒體：「你們要美國繼續被腐敗的政治階級統治，或者再次由人民作主？」他要選民「夢想大一點」，允諾終結「背叛的歲月」，將撕毀貿易協定、封鎖邊境、驅散敘利亞難民：「我與你們同在，為你們奮戰，且我們會勝利。」台下支持者高呼：「希拉蕊是惡魔！」「她是女巫！」 

外交部密切觀察
我行政院長林全昨表示，不論最後哪一位當選，都期待新的領導人，能對世界繁榮和平及永續發展，做出更多的貢獻。我外交部表示，台美關係密切友好，我駐美國代表處及駐美各辦事處平日即與民主、共和兩黨全國委員會及地方性組織保持聯繫與交流，外交部及駐美代表處也已成立專案小組密切觀察並研析呈報。 

美國大選觀選指南
●關鍵數字：
．除緬因和內布拉斯加兩州外，各州均採「贏者全拿」制度，即在該州拿最多普選票者，可獲該州全部選舉人票。美國50州及華府共538張選舉人票，獲270張選舉人票者，即可入主白宮
●投票結束：
．阿拉斯加州於台灣時間今下午2時關閉投票所，所有投票結束
●總統開票：
．預計台灣時間今中午12時，加州結束投票後，可知誰是總統贏家。上屆加州開票約15分鐘後，媒體便依出口民調預測歐巴馬連任成功
●其他選舉：
．國會眾議院435席全改選；參議院100席要改選34席
．猶他等12州有州長選舉
．另有地方議會議員、法官、市長、警長等選舉
．35州舉行公投，如加州公投表決是否要求A片演員戴套
資料來源：綜合外電 

'''

In [12]:
import jieba
jieba.load_userdict("userdict.txt")

word_list = []
for word in jieba.cut(apple):
    word_list.append(word)

## 用字典統計字詞

In [14]:
a = ['a', 'b', 'c', 'a', 'b', 'a']
count_dic = {}
for ele in a:
    if ele not in count_dic:
        count_dic[ele] = 1
    else:
        count_dic[ele] = count_dic[ele] + 1
count_dic

{'a': 3, 'b': 2, 'c': 1}

In [27]:
import jieba
jieba.load_userdict("userdict.txt")

# 使用Jieba 切詞
word_list = []
for word in jieba.cut(apple):
    word_list.append(word)

# 用字典統計字詞
count_dic = {}
for word in word_list:
    if word not in count_dic:
        count_dic[word] = 1
    else:
        count_dic[word] = count_dic[word] + 1

In [28]:
import operator
swd = sorted(count_dic.items(), key=operator.itemgetter(1), reverse=True)

In [32]:
for item in swd:
    #print(item)
    word, cnt =item
    if len(word) >= 2 and cnt >= 4:
        print(word, cnt)

川普 14
投票 14
希拉蕊 13
當選 5
提前 5
支持者 5
拉丁裔 5
選舉人票 5
美國 4
台灣 4
時間 4
造勢 4
開票 4
女性 4
領先 4
城鎮 4
媒體 4
總統 4


## 使用 Counter 做統計
- https://docs.python.org/3.5/library/collections.html

In [34]:
a = ['a', 'b', 'c', 'a', 'b', 'a']

from collections import Counter
c = Counter(a)
c

Counter({'a': 3, 'b': 2, 'c': 1})

In [35]:
c.most_common(2)

[('a', 3), ('b', 2)]

In [38]:
import jieba
jieba.load_userdict("userdict.txt")

# 使用Jieba 切詞
word_list = []
for word in jieba.cut(apple):
    if len(word) >=2:
        word_list.append(word)

# 用Counter統計字詞
from collections import Counter
c = Counter(word_list)

In [41]:
for word, cnt in c.most_common(20):
    print(word, cnt)

投票 14
川普 14
希拉蕊 13
當選 5
提前 5
支持者 5
拉丁裔 5
選舉人票 5
美國 4
台灣 4
時間 4
開票 4
媒體 4
領先 4
城鎮 4
女性 4
造勢 4
總統 4
加州 3
北卡羅萊納州 3


## 分析當日所有蘋果新聞頭條詞頻

In [45]:
import requests
from bs4 import BeautifulSoup

newslist = []
## 抓取每頁分頁清單
for page in range(1,31):
    res = requests.get('http://www.appledaily.com.tw/realtimenews/section/new/{}'.format(page))
    soup = BeautifulSoup(res.text, 'html.parser')
    # 根據清單拿出標題
    for news in soup.select('.rtddt a'):
        title = news.select('h1')[0].text
        newslist.append(title)
        #print(news.select('h1')[0].text)
        #print('=============================')

In [61]:
import jieba
import re
jieba.load_userdict("userdict.txt")

# 資料清理
word_list = []
for entry in newslist:
    news = entry
    
    if entry.find('】') > 0 :
        news = news.split('】')[1]
    if entry.find('...') > 0:
        news = news.split('...')[0]
    if entry.find('(') > 0:
        news = news.split('(')[0]
    # 篩選字詞長度 >=2 以及是中文的字詞
    for word in jieba.cut(news):
        if len(word) >= 2 and re.match('[\u4e00-\u9fa5]+', word):
            word_list.append(word)

In [64]:
from collections import Counter
# 使用Collections 的 Counter 進行統計
c = Counter(word_list)
for word, cnt in c.most_common(30):
    print(word, cnt)

川普 34
希拉蕊 23
投票 19
台灣 16
美國 15
馬英九 13
中國 11
明年 11
總統 11
美大選 10
這樣 10
網友 9
日本 9
女友 8
釋法 8
香港 7
人大 7
抗議 7
美國大選 7
正妹 6
全球 6
大選 6
朴槿惠 6
女主播 6
億元 6
選舉 6
結果 6
十一月 6
醫療 6
蘋果 5


## TF-IDF 計算

In [65]:
a, abb, abc = ["a"], ["a","b","b"], ["a","b","c"]
D=[a,abb,abc]

In [69]:
# tfidf("a", a, D)
import scipy

tf    =  1 / 1
idf   =  scipy.log(3 / 3)
tf, idf, tf * idf

(1.0, 0.0, 0.0)

In [74]:
# tfidf("b", abb, D)
tf  = 2 / 3
idf = scipy.log(3 / 2)
tf, idf, tf * idf

(0.6666666666666666, 0.40546510810816438, 0.27031007207210955)

In [76]:
# tfidf("a",abc,D)
tf  = 1 / 3
idf = scipy.log(3/3)
tf, idf, tf * idf

(0.3333333333333333, 0.0, 0.0)

In [79]:
# tfidf("b",abc,D)
tf = 1 / 3
idf = scipy.log(3/2)
tf, idf, tf*idf

(0.3333333333333333, 0.40546510810816438, 0.13515503603605478)

In [81]:
# tfidf("c",abc,D)
tf  = 1 / 3
idf = scipy.log(3/1)
tf, idf, tf * idf

(0.3333333333333333, 1.0986122886681098, 0.36620409622270322)

In [82]:
a = ['a', 'b', 'c', 'a', 'a']
a.count('a')

3

In [84]:
a, abb, abc = ["a"], ["a","b","b"], ["a","b","c"]
D=[a,abb,abc]

2

In [ ]:
# 正規作法
doc_contains_term = []
for doc in D:
    if 'b' in doc:
        doc_contains_term.append(doc)
len(doc_contains_term)

In [85]:
# 一行文作法
len([doc for doc in D if 'b' in doc])

2

## 建立 tf * idf 函式

In [97]:
def tfidf(term, doc, D):
    tf  =  doc.count(term)  / len(doc)
    idf =  scipy.log(len(D) /  len([d for d in D if term in d]))
    return tf * idf

In [98]:
# 第二版: 分母 + 1
def tfidf2(term, doc, D):
    tf  =  doc.count(term)  / len(doc)
    idf =  scipy.log(len(D) /  (len([d for d in D if term in d]) + 1 ))
    return tf * idf

In [99]:
print(tfidf("a",a,D))
print(tfidf("b",abb,D))
print(tfidf("a",abc,D))
print(tfidf("b",abc,D))
print(tfidf("c",abc,D))

0.0
0.270310072072
0.0
0.135155036036
0.366204096223


## 建立詞頻矩陣

In [104]:
s = '【更新】柯P：洪智坤洩漏公文案還沒看到公文今處理'
#for w in jieba.cut(s):
#    print(w)
' '.join(jieba.cut(s))

'【 更新 】 柯P ： 洪智坤 洩漏 公文 案還 沒 看到 公文 今處理'

In [114]:
jieba.load_userdict("userdict.txt")
ary=['【更新】柯P：洪智坤洩漏公文案還沒看到公文今處理',
     '留洪智坤 柯：殘障求職不易',
     '人事處議處洪智坤 柯P：不清楚議處結果']

corpus = []
for title in ary:
    corpus.append(' '.join(jieba.cut(title)))

In [116]:
corpus

['【 更新 】 柯P ： 洪智坤 洩漏 公文 案還 沒 看到 公文 今處理',
 '留 洪智坤   柯 ： 殘障 求職 不易',
 '人事 處議 處 洪智坤   柯P ： 不 清楚 議處 結果']

In [117]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

- '【更新】柯P：洪智坤洩漏公文案還沒看到公文今處理',
- '留洪智坤 柯：殘障求職不易',
- '人事處議處洪智坤 柯P：不清楚議處結果']

In [118]:
word=vectorizer.get_feature_names()
print(' '.join(word))
print(X.toarray())

不易 人事 今處理 公文 更新 柯p 案還 殘障 求職 洩漏 洪智坤 清楚 看到 結果 處議 議處
[[0 0 1 2 1 1 1 0 0 1 1 0 1 0 0 0]
 [1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 1 1 0 1 1 1]]


## 計算tf-idf 權值

In [121]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer=TfidfTransformer()
tfidf=transformer.fit_transform(X)
weight=tfidf.toarray()
print(weight)

[[ 0.          0.          0.31738473  0.63476946  0.31738473  0.24137927
   0.31738473  0.          0.          0.31738473  0.18745253  0.
   0.31738473  0.          0.          0.        ]
 [ 0.54645401  0.          0.          0.          0.          0.          0.
   0.54645401  0.54645401  0.          0.32274454  0.          0.          0.
   0.          0.        ]
 [ 0.          0.41074684  0.          0.          0.          0.31238356
   0.          0.          0.          0.          0.2425937   0.41074684
   0.          0.41074684  0.41074684  0.41074684]]


## 計算cosine similarity

In [123]:
from sklearn.metrics import pairwise
?pairwise.cosine_similarity

In [126]:
import numpy
from sklearn.metrics.pairwise import cosine_similarity

X = numpy.array([1, 2, 2, 1, 1, 1, 0])
Y = numpy.array([1, 2, 2, 1, 1, 2, 1])

cosine_similarity(X,Y)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 0.93819419]])

## 建立詞頻矩陣的相似度

In [127]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [128]:
cosine_similarity(X)

array([[ 1.        ,  0.15075567,  0.22792115],
       [ 0.15075567,  1.        ,  0.18898224],
       [ 0.22792115,  0.18898224,  1.        ]])

## 建立tfidf矩陣的相似度

In [129]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer=TfidfTransformer()
tfidf=transformer.fit_transform(X)

In [130]:
cosine_similarity(tfidf)

array([[ 1.        ,  0.06049928,  0.12087772],
       [ 0.06049928,  1.        ,  0.07829579],
       [ 0.12087772,  0.07829579,  1.        ]])

In [132]:
cosine_similarity(tfidf[0], tfidf)

array([[ 1.        ,  0.06049928,  0.12087772]])

In [135]:
cosine_similarities = cosine_similarity(tfidf[0], tfidf).flatten()
cosine_similarities

array([ 1.        ,  0.06049928,  0.12087772])

## 找出相關文章

In [146]:
cosine_similarities.argsort()[::-1]
print('查詢文章:', ary[0])
for idx in cosine_similarities.argsort()[::-1][1:]:
    print('相關文章:',ary[idx], cosine_similarities[idx])

查詢文章: 【更新】柯P：洪智坤洩漏公文案還沒看到公文今處理
相關文章: 人事處議處洪智坤 柯P：不清楚議處結果 0.120877716968
相關文章: 留洪智坤 柯：殘障求職不易 0.0604992822195


## argsort v.s. sort

In [138]:
a = [3,1,2,5,4]
a.sort()
a

[1, 2, 3, 4, 5]

In [141]:
a = [3,1,2,5,4]
b = numpy.array(a)
b = b.argsort()
b

array([1, 2, 0, 4, 3], dtype=int64)

## 蒐集蘋果新聞資料爬蟲

In [148]:
import requests
from bs4 import BeautifulSoup
domain  = 'http://www.appledaily.com.tw'
urllist = []
## 抓取每頁分頁清單
for page in range(1,31):
    res = requests.get('http://www.appledaily.com.tw/realtimenews/section/new/{}'.format(page))
    soup = BeautifulSoup(res.text, 'html.parser')
    # 根據清單拿出標題
    for news in soup.select('.rtddt a'):
        url = domain + news['href']
        urllist.append(url)
        

In [153]:
def getNewsContent(url):
    try:
        res = requests.get(url)
        soup = BeautifulSoup(res.text, 'html.parser')
        title   = soup.select('#h1')[0].text.strip()
        content = soup.select('#summary')[0].text.strip()
        return {'title':title, 'content':content}
    except:
        return None

In [154]:
getNewsContent('http://www.appledaily.com.tw/realtimenews/article/life/20161109/985027/%E6%9D%B1%E5%8C%97%E5%AD%A3%E9%A2%A8%E7%99%BC%E5%A8%81%E3%80%80%E5%8F%B0%E5%8C%97%E7%AD%898%E6%B8%AC%E7%AB%99%E5%89%B5%E5%85%A5%E5%86%AC%E6%9C%80%E4%BD%8E%E6%BA%AB')

{'content': '受到東北季風影響，淡水今天清晨出現16.8℃，寫下入冬以來平地最低溫紀錄，另外包括新竹17.8℃、蘇澳18℃、基隆與板橋的18.4℃、台北18.6℃、梧棲18.7℃、台中19.9℃，都寫下該測站入冬最低溫紀錄，等於有8個測站都創下入冬最低溫。氣象局表示，今起到周五都受東北季風影響，北台灣濕冷、低溫下探18℃，不排除有更低溫，中南部低溫在19至20℃，各地早晚偏涼，中南部日夜溫差大，預計周末東北季風減弱，但北台灣仍有短暫雨，預計下周一才會明顯轉趨穩定。（生活中心／台北報導）',
 'title': '東北季風發威\u3000台北等8測站創入冬最低溫'}

In [155]:
applenews = [getNewsContent(url) for url in urllist]

In [157]:
import pandas
df = pandas.DataFrame(applenews)
df.to_excel('20161109news.xlsx')

## 讀取蘋果新聞

In [1]:
import pandas
df = pandas.read_excel('20161109news.xlsx')
df.head()

content                    title
0  川普打敗希拉蕊，成為美國新任總統。在德洲長大的美籍藝人Janet今出席活動，對川普當選，在德...   川普當選美總統　Janet「不要只想到自己」
1  從事桃園機場接送的楊姓、紀姓司機，今年初不滿林姓同業降價接單，在「派趟勿喇賽」、「市區派趟聊...       不滿削價接客　公開同業姓名、手機判拘
2  (更新:新增過音影片)台中新社花海11月5日才開幕，就有網友向《蘋果》投訴指出，臉書發現有不...     花海拍美照踩死花　民眾爆料批「沒公德心」
3  美國共和黨總統候選人川普（Donald Trump）極有可能成為下屆美國總統，不但異於過去多...        人民選擇川普　諾貝爾桂冠：「絕望」
4  （更新：卡卡推特　美國隊長推特）美國總統大選開票接近尾聲，原本外界看好的希拉蕊一路落後給川普...  【好萊塢哀號】川普贏了！ 美國隊長怒喊「丟臉」

In [33]:
df[df.content.str.contains('馬英九')]

content  \
18   美國總統大選開票結果即將出爐之際，國民黨下午3時22分發出「洪主席恭賀川普當選美國總統」新聞...   
189  羅伯特亞當斯／自由作家2013年9月間爆發「馬王政爭」，檢察總長夜奔總統官邸密告官場大咖的諸...   
351  前總統馬英九遭民進黨立委柯建銘自訴洩密等罪，台北地院昨首度以被告身分傳馬出庭，馬英九與柯建銘...   
416  前總統馬英九自卸任元首職務後，司法單位陸續針對他涉及的司法案件展開調查，為了3年前的馬王政爭...   
428  蘋果日報頭條今天揭曉 美首位女總統？ 瘋狂素人總統？全球矚目的美國大選，昨天投票，究竟美國將...   
474  2013年9月8日前總統馬英九在總統府舉行記者會，痛斥立法院前院長王金平司法關說，開啟「馬王...   
551  （更新：新增動新聞）前總統馬英九遭民進黨立委柯建銘自訴涉嫌洩密等罪，台北地院今天下午將首度以...   
606  ●【有片】超誇張 婦人7年家用垃圾都丟美麗華百貨http://ppt.cc/2Z92F●【不...   
614  前總統馬英九今天下午為立委柯建銘自訴他涉嫌洩密等罪到台北地院應訊，台北地院為讓更多民眾可以旁...   
648  民進黨立院黨團總召集人柯建銘自訴前總統馬英九洩密案，馬英九下午首度以被告身分到台北地院出庭。...   
806  前總統馬英九遭立委柯建銘自訴涉嫌洩密、加重誹謗，今天下午馬英九首度出庭，這也是他卸任後，首度...   
811  民進黨立院黨團總召柯建銘自訴前總統馬英九洩密案，馬下午首度以被告身分到台北地院出庭之際，馬英...   
815  民進黨立委柯建銘自訴前總統馬英九洩密案，馬下午首度以被告身分到台北地院出庭，前副總統吳敦義接...   
818  前總統馬英九遭民進黨立院黨團總召柯建銘自訴涉嫌洩密等罪，下午首度以被告身分出席。總統府前副秘...   
834  （更新：新增影片）高等法院今上午開庭審理前總統馬英九自訴控告名嘴周玉蔻涉犯加重誹謗案，馬與證...   
853  (更新:新增影片)前總統馬英九今天下午將針對民進黨立委柯建銘自訴控告洩密等案，到北院出庭應訊...   

                                             title  
18                            國民黨搶頭香　洪秀柱第一時間恭賀川普當選  
189                                      「洩密門」的總統學  
351                           馬英九、柯建銘當庭交鋒　柯要求法院這樣做  
416                          【壹週刊】馬英九出庭　法界：教唆洩密恐成罪  
428                                   十一月九日各報頭條搶先報  
474                     【有恨片】318學運漫延　就是因為馬英九只考慮那2秒  
551                           柯建銘律師聲請羈押馬英九　北院：另案裁定  
606  【鄉民焦點】無極限！奧客家裡垃圾7年都丟美麗華竟無法罰●希拉蕊or川普？美國新總統明午誕生  
614                             馬英九柯建銘法庭論戰　民眾只給60分  
648                           洪秀柱批柯建銘報私仇　「企圖羞辱馬英九」  
806                               馬英九挨告首出庭　148字捍清白  
811                      【出庭聲明】馬英九：我沒犯罪　任何人都不應司法關說  
815                    【還原馬王政爭】吳敦義自爆「鍘王」前　馬英九曾猶豫2秒  
818                           羅智強：台灣的是非　被一群無臉人埋進棺材  
834                          柯建銘告馬英九今開庭　周玉蔻預言「他」會贏  
853                        【交手片】馬英九出庭應訊　柯建銘：怎有臉跟我辯

In [2]:
df = df.dropna()

In [8]:
import jieba
jieba.load_userdict("userdict.txt")
corpus = []
titles = []
for news in df.iterrows():    
    titles.append(news[1].title)
    corpus.append(' '.join(jieba.cut(news[1].content)))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\cathay\AppData\Local\Temp\jieba.cache
Loading model cost 1.269 seconds.
Prefix dict has been built succesfully.


In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [10]:
word=vectorizer.get_feature_names()
len(word)

36311

In [11]:
X.shape

(899, 36311)

In [12]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer=TfidfTransformer()
tfidf=transformer.fit_transform(X)

In [13]:
tfidf.shape

(899, 36311)

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarities = cosine_similarity(tfidf, tfidf)

In [20]:
titles[0]
for idx in cosine_similarities[0].argsort()[::-1]:
    if  cosine_similarities[0][idx] > 0.1:
        print(titles[idx],  cosine_similarities[0][idx])

川普當選美總統　Janet「不要只想到自己」 1.0
Janet崩潰暴哭「很孤單」　揭憂鬱病史絕望吶喊 0.147133807474
川普若當選　台灣學者：亞太國家都要重新上課 0.106005826482
美大選陷入拉鋸　學者：唐鳳酸川普「眼睛有業障」不妥 0.105698950312


In [21]:
def getSimiliarArticle(articleid):
    print('查詢新聞:', titles[articleid])
    for idx in cosine_similarities[articleid].argsort()[::-1][1:]:
        if  cosine_similarities[articleid][idx] > 0.1:
            print('相關新聞:', titles[idx],  cosine_similarities[0][idx])

In [34]:
getSimiliarArticle(351)

查詢新聞: 馬英九、柯建銘當庭交鋒　柯要求法院這樣做
相關新聞: 柯建銘律師聲請羈押馬英九　北院：另案裁定 0.0196625263899
相關新聞: 馬英九挨告首出庭　148字捍清白 0.0174159405854
相關新聞: 【出庭聲明】馬英九：我沒犯罪　任何人都不應司法關說 0.0183971813619
相關新聞: 洪秀柱批柯建銘報私仇　「企圖羞辱馬英九」 0.0130120227732
相關新聞: 羅智強：台灣的是非　被一群無臉人埋進棺材 0.0297148629537
相關新聞: 【交手片】馬英九出庭應訊　柯建銘：怎有臉跟我辯 0.0111998901418
相關新聞: 【壹週刊】馬英九出庭　法界：教唆洩密恐成罪 0.00768503197906
相關新聞: 「洩密門」的總統學 0.012359177879
相關新聞: 柯建銘告馬英九今開庭　周玉蔻預言「他」會贏 0.0100006164601
相關新聞: 十一月九日各報頭條搶先報 0.0763571766517
相關新聞: 【有恨片】318學運漫延　就是因為馬英九只考慮那2秒 0.0216065908631
相關新聞: 【還原馬王政爭】吳敦義自爆「鍘王」前　馬英九曾猶豫2秒 0.0179290824918
相關新聞: 馬英九柯建銘法庭論戰　民眾只給60分 0.0232490516328
相關新聞: 台南地院修復啟用　賴清德致詞洗臉司法院長 0.0111318188693
相關新聞: 邱太三明拜會許宗力　最高法院可望常態辯論 0.0123889236389
